In [1]:
import pandas as pd
import numpy as np

In [44]:
pd.options.display.float_format = '{:,.2f}'.format
pd.set_option('display.max_rows', None)

In [ ]:
import re
from io import StringIO

# Read and clean the file content
with open(file_path, 'r') as f:
    content = f.read()

# Remove spaces between closing quote and delimiter: "Value"   | -> "Value"|
cleaned_content = re.sub(r'"\s+\|', '"|', content)

# Parse the cleaned content
df = pd.read_csv(StringIO(cleaned_content), sep='|', skipinitialspace=True, engine='python')
df.columns = df.columns.str.strip()

print("Data loaded successfully.")

In [9]:
# Display first few rows
df.head()

,create_at,type,counterparty,Product country,Product ID,Product name,Item ID,Item name,Amount,Currency,Qty
0,2026-02-01 03:59:59.674247+04,DTU_PURCHASE,USD | Xsolla,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,3.2443,USD,1
1,2026-02-01 03:59:59.674247+04,DTU_SALE,USDT | Dessley,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,3.2955,USD,1
2,2026-02-01 03:59:58.815653+04,DTU_PURCHASE,USD | Xsolla,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,0.0950,USD,1
3,2026-02-01 03:59:58.815653+04,DTU_SALE,USDT | Dessley,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,0.0965,USD,1
4,2026-02-01 03:59:57.907522+04,DTU_SALE,USDT | Dessley,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,0.0965,USD,1

In [16]:
# Basic info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3490199 entries, 0 to 3490198
Data columns (total 11 columns):
 #   Column           Dtype
---  ------           -----
 0   create_at        str
 1   type             str
 2   counterparty     str
 3   Product country  str
 4   Product ID       int64
 5   Product name     str
 6   Item ID          int64
 7   Item name        str
 8   Amount           float64
 9   Currency         str
 10  Qty              int64
dtypes: float64(1), int64(3), str(7)
memory usage: 292.9 MB

In [28]:
df['create_at'] = pd.to_datetime(df['create_at'])
df['created_at_ymd'] = df['create_at'].dt.date
df['created_at_ym'] = df['create_at'].dt.to_period('M')

/var/folders/1b/7_zgcknn10j782nt1hr38p8w0000gr/T/ipykernel_14344/186920313.py:3: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df['created_at_ym'] = df['create_at'].dt.to_period('M')

In [ ]:
dfusd = df[df["Currency"].isin(["USD", "USDT", "USDC"])]# 1. Сначала подготавливаем агрегированную таблицу
df

,create_at,type,counterparty,Product country,Product ID,Product name,Item ID,Item name,Amount,Currency,Qty,created_at_ymd,created_at_ym
0,2026-02-01 03:59:59.674247+04:00,DTU_PURCHASE,USD | Xsolla,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,3.24,USD,1,2026-02-01,2026-02
1,2026-02-01 03:59:59.674247+04:00,DTU_SALE,USDT | Dessley,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,3.30,USD,1,2026-02-01,2026-02
2,2026-02-01 03:59:58.815653+04:00,DTU_PURCHASE,USD | Xsolla,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,0.10,USD,1,2026-02-01,2026-02
3,2026-02-01 03:59:58.815653+04:00,DTU_SALE,USDT | Dessley,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,0.10,USD,1,2026-02-01,2026-02
4,2026-02-01 03:59:57.907522+04:00,DTU_SALE,USDT | Dessley,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,0.10,USD,1,2026-02-01,2026-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3490194,2026-01-01 04:00:02.714076+04:00,VOUCHER_PURCHASE,USD | Content Card,US,62,Steam Wallet Code | US,395,$25 Steam Wallet Code,23.75,USD,1,2026-01-01,2026-01
3490195,2026-01-01 04:00:01.996405+04:00,DTU_PURCHASE,USD | Xsolla,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,0.10,USD,1,2026-01-01,2026-01
3490196,2026-01-01 04:00:01.996405+04:00,DTU_SALE,USDT | Dessley,CIS,441,Steam Wallet Top Up | CIS,3143,Steam Wallet Top Up | CIS,0.10,USD,1,2026-01-01,2026-01
3490197,2026-01-01 04:00:01.816653+04:00,VOUCHER_PURCHASE,AED | LikeCard,OM,497,Ooredoo Voucher | OM,3449,OMR 2 Ooredoo Prepaid Voucher,18.74,AED,1,2026-01-01,2026-01
3490198,2026-01-01 04:00:01.499710+04:00,VOUCHER_PURCHASE,USD | Content Card,US,62,Steam Wallet Code | US,392,$5 Steam Wallet Code,4.75,USD,1,2026-01-01,2026-01

In [30]:
df["created_at_ym"].value_counts()

created_at_ym
2026-01    3483533
2026-02       6666
Freq: M, Name: count, dtype: int64

In [ ]:
df[df["created_at_ym"] == "2026-02"]

In [48]:
df[df["created_at_ym"] == "2026-01"].groupby(["Product name","Item name"]).agg(
    Sum_Amount=("Amount", "sum"), 
    Mean_Amount=("Amount", "mean"), 
    Currency = ("Currency", "first"),
    Quantity=("Qty", "sum")  # Ensure this column name matches your data (e.g., 'Quantity' or 'Qty')
).sort_values(by="Quantity", ascending=False).reset_index().head(50)

,Product name,Item name,Sum_Amount,Mean_Amount,Currency,Quantity
0,Steam Wallet Top Up | CIS,Steam Wallet Top Up | CIS,"18,619,549.47",8.31,USD,2240626
1,PlayStation®Store Wallet | TR,TRY 250 PlayStation®Store Wallet gift card,"1,173,091.99",21.76,USD,65846
2,PlayStation®Store Wallet | TR,TRY 500 PlayStation®Store Wallet gift card,"795,027.97",19.92,USD,49296
3,PlayStation®Store Wallet | US,$10 PlayStation®Store Wallet gift card,"523,616.84",21.72,USD,31713
4,PUBG Mobile Top Up,PUBG Mobile: 60 UC,"27,020.15",0.88,USDT,30798
5,du eVoucher | AE,AED 30 du eVoucher,"899,195.36",54.02,AED,30639
6,PlayStation®Store Wallet | TR,TRY 1000 PlayStation®Store Wallet gift card,"1,119,422.16",53.85,USD,26676
7,App Store & iTunes Code | RU,RUB 500 App Store & iTunes Gift Code,"173,507.55",87.54,EUR,25981
8,Apple Gift Card | US,$2 Apple Gift Card,"42,878.64",2.21,USD,22610
9,PUBG Mobile Gift Card,PUBG Mobile: 60 UC,"23,668.29",2.78,AED,22306
10,Jazz Pakistan,PKR 630 Recharge,"115,478.38",5.34,AED,21628
11,PUBG Mobile Top Up,PUBG Mobile: 300 + 25 UC,"82,527.07",4.40,USDT,18762
12,Apple Gift Card | US,$10 Apple Gift Card,"167,328.21",10.52,USD,17489
13,Jio India,INR 299 Bundle,"2,195,472.86",144.42,INR,15202
14,PUBG Mobile Top Up,PUBG Mobile: 600 + 60 UC,"129,274.41",8.76,USD,14754
15,Jazz Pakistan,PKR 315 Recharge,"35,776.37",2.65,AED,13524
16,Zong Pakistan,PKR 630 Recharge,"70,252.04",5.25,AED,13390
17,PlayStation®Store Wallet | TR,TRY 1500 PlayStation®Store Wallet gift card,"798,178.62",73.16,USD,13012
18,Roblox Gift Card | US,$10 Roblox gift card,"125,334.89",12.04,USD,12948
19,Ncell Nepal,NPR 150 Credit,"31,656.66",2.61,AED,12142
20,Apple Gift Card | US,$5 Apple Gift Card,"59,042.16",5.90,USD,12113
21,Ncell Nepal,NPR 300 Credit,"61,993.31",5.21,AED,11896
22,Minecraft for PC,Minecraft: Java & Bedrock Edition for PC,"326,471.69",55.62,USD,11895
23,PUBG Mobile Gift Card,PUBG Mobile: 660 UC,"146,664.06",19.74,AED,11760
24,Airtel India,INR 199 Bundle,"1,105,139.15",96.20,INR,11488
25,PlayStation®Store Wallet | US,$25 PlayStation®Store Wallet gift card,"471,097.07",51.36,USD,11341
26,Airtel India,INR 349 Bundle,"1,904,387.00",168.71,AED,11288
27,Airtel India,INR 299 Bundle,"1,628,962.10",144.54,INR,11270
28,Xbox Gift Card | ZA,ZAR 120 Xbox gift card,"157,764.29",26.87,AED,10868
29,Salik eVoucher | AE,AED 50 Salik eVoucher,"493,652.50",49.56,AED,9960
30,PlayStation®Store Wallet | TR,TRY 750 PlayStation®Store Wallet gift card,"166,328.82",20.70,USD,9959
31,PlayStation®Store Wallet | TR,TRY 2000 PlayStation®Store Wallet gift card,"589,059.25",73.90,USD,9688
32,PlayStation®Store Wallet | US,$50 PlayStation®Store Wallet gift card,"845,125.88",109.01,USD,9551
33,NTC Nepal,NPR 150 Call Credit,"23,747.27",2.59,USD,9172
34,Xbox Gift Card | ZA,ZAR 100 Xbox gift card,"110,818.35",22.13,AED,9160
35,Steam Wallet Code | US,$10 Steam Wallet Code,"89,200.44",27.19,USD,9130
36,PUBG Mobile Gift Card,PUBG Mobile: 325 UC,"74,816.07",9.88,USD,9063
37,Google Play Gift Code | AE,AED 30 Google Play gift card,"250,385.96",28.92,AED,8658
38,Virgin Mobile Voucher | AE,AED 20 Virgin Mobile Voucher,"167,370.44",19.42,AED,8617
39,Apple Gift Card | US,$20 Apple Gift Card,"163,446.45",21.62,USD,8462
40,NTC Nepal,NPR 300 Call Credit,"43,071.22",5.17,AED,8324
41,Steam Wallet Code | HK,HKD 40 Steam Wallet Code,"39,916.19",17.01,USD,8213
42,Apple Gift Card | AE,AED 50 Apple gift card,"387,545.58",48.39,AED,8060
43,Steam Wallet Code | VN,VND 132500 Steam Wallet Code,"39,306.74",7.15,USD,8036
44,Zong Pakistan,PKR 315 Recharge,"20,696.75",2.62,USD,7886
45,Xbox Gift Card | ZA,ZAR 50 Xbox gift card,"46,973.72",11.53,AED,7770
46,Valorant Gift Card | US,$15 Valorant gift card | 1520 VP,"105,200.00",57.90,USD,7733
47,Roblox Code,Roblox: 800 Robux code,"69,348.03",12.89,USD,7593
48,Riot Cash Card | US,$15 Riot Cash card,"101,399.74",786.04,USD,7434
49,PUBG Mobile Top Up,PUBG Mobile: 1500 + 300 UC,"162,686.93",22.00,USD,7394

In [ ]:

grouped_df = dfusd[dfusd["created_at_ym"] == "2026-01"].groupby(["Product name", "Item name"]).agg(
    Sum_Amount=("Amount", "sum"), 
    Mean_Amount=("Amount", "mean"), 
    Currency=("Currency", "first"),
    Quantity=("Qty", "sum")
).reset_index()

# 2. Задаем диапазоны (границы) и подписи
# 0-10, 10-100, 100-1000, 1000-20000, 20000+
bins = [0, 10, 100, 1000, 20000, float('inf')]
labels = ['до 10', '10-100', '100-1000', '1000-20000', 'выше 20т']

# 3. Разбиваем колонку Quantity на категории
# right=False означает, что левая граница включена, а правая нет (например, 10 попадет в '10-100')
grouped_df['Range'] = pd.cut(grouped_df['Quantity'], bins=bins, labels=labels, right=False)

summary_table = grouped_df.groupby('Range').agg(
    Count=('Product name', 'count'),       # Количество товаров в диапазоне
    Total_Sum=('Sum_Amount', 'sum')        # Общая сумма продаж в диапазоне
)

summary_table

            Count     Total_Sum
Range
до 10        1094    215,532.09
10-100       1099  1,785,544.38
100-1000      562 11,292,182.24
1000-20000    270 43,772,173.01
выше 20т       11 23,512,456.80